-- Owner onboarding.
--
-- THE CHICKEN AND EGG
-- -------------------
-- Every policy in migration 300 derives access from an *active membership*. A
-- brand-new user has none, which is correct — and it means they cannot insert
-- an organization, because the WITH CHECK asks whether they are a member of an
-- organization that does not exist yet.
--
-- This is the one place a SECURITY DEFINER function is genuinely the right
-- answer rather than a way to silence an RLS error. It creates the organization,
-- the owner membership, the first location, and the first stand together, so a
-- half-finished signup cannot leave a user owning nothing or an organization
-- with no owner.
--
-- It is safe because it takes no organization id: it always creates a *new* one
-- and always makes the caller its owner. There is no argument an attacker can
-- supply that attaches them to somebody else's tenant.
--
-- Unlike the public flow's functions, this one is callable by `authenticated` —
-- the caller is a real signed-in user, and `auth.uid()` is checked rather than
-- trusted from a parameter.

-- How many organizations one user may own. Not a business rule so much as an
-- abuse bound: without it, one account can mint unlimited tenants and every
-- per-tenant limit becomes meaningless.
create or replace function app.owned_organization_limit() returns integer
language sql immutable set search_path = '' as $$ select 10 $$;

/**
 * Create an organization, its owner, its first location, and its first stand.
 *
 * Returns the ids so the caller can immediately show the owner their new stand.
 * The stand token itself is generated by the application and passed in already
 * digested — this function never sees it, which keeps the "the raw token is
 * never stored" property true even here.
 */
create or replace function app.create_organization_with_first_stand(
    p_name                text,
    p_slug                text,
    p_timezone            text,
    p_default_locale      text,
    p_location_name       text,
    p_google_review_url   text,
    p_stand_token_hash    text,
    p_stand_token_prefix  text,
    p_stand_label         text,
    p_token_key_version   smallint,
    p_request_id          text default null
)
returns table (org_id uuid, location_id uuid, stand_id uuid)
language plpgsql
security definer
set search_path = ''
as $$
declare
    actor        uuid := (select auth.uid());
    new_org      uuid;
    new_location uuid;
    new_stand    uuid;
    owned        integer;
begin
    -- Validated, never taken from a parameter. A function that accepted a user
    -- id would let any caller create an organization owned by someone else.
    if actor is null then
        raise exception 'authentication required' using errcode = '42501';
    end if;

    select count(*) into owned
      from public.organization_members m
     where m.user_id = actor and m.role = 'owner' and m.status = 'active';

    if owned >= app.owned_organization_limit() then
        raise exception 'organization limit reached' using errcode = '54000';
    end if;

    insert into public.organizations (name, slug, timezone, default_locale)
    values (p_name, p_slug, coalesce(p_timezone, 'UTC'), coalesce(p_default_locale, 'en'))
    returning id into new_org;

    -- The caller becomes the owner in the same statement batch as the
    -- organization, so there is no window in which an organization exists with
    -- nobody able to administer it.
    insert into public.organization_members (org_id, user_id, role, status, joined_at)
    values (new_org, actor, 'owner', 'active', now());

    insert into public.locations
        (org_id, name, timezone, default_locale, google_review_url)
    values
        (new_org, p_location_name, coalesce(p_timezone, 'UTC'),
         coalesce(p_default_locale, 'en'), p_google_review_url)
    returning id into new_location;

    -- A business with no stand cannot collect anything, so one is always
    -- created. It is active immediately; the public flow refuses to serve it
    -- until the location has a validated Google URL, which keeps a
    -- half-configured stand from showing a customer a broken page.
    insert into public.review_stands
        (org_id, location_id, public_token_hash, public_token_prefix, label,
         stand_type, status, activated_at, public_token_key_version)
    values
        (new_org, new_location, p_stand_token_hash, p_stand_token_prefix,
         coalesce(p_stand_label, 'Front Desk'), 'printable_qr', 'active', now(),
         coalesce(p_token_key_version, 1))
    returning id into new_stand;

    insert into public.audit_events
        (org_id, actor_user_id, actor_type, action, target_type, target_id, request_id, metadata)
    values
        (new_org, actor, 'user', 'organization.created', 'organization', new_org::text,
         p_request_id, jsonb_build_object('locationId', new_location, 'standId', new_stand));

    return query select new_org, new_location, new_stand;
end;
$$;

create or replace function public.rpc_create_organization(
    p_name                text,
    p_slug                text,
    p_timezone            text,
    p_default_locale      text,
    p_location_name       text,
    p_google_review_url   text,
    p_stand_token_hash    text,
    p_stand_token_prefix  text,
    p_stand_label         text,
    p_token_key_version   smallint,
    p_request_id          text default null
)
returns table (org_id uuid, location_id uuid, stand_id uuid)
language sql
security invoker
set search_path = ''
as $$
    select * from app.create_organization_with_first_stand(
        p_name, p_slug, p_timezone, p_default_locale, p_location_name,
        p_google_review_url, p_stand_token_hash, p_stand_token_prefix,
        p_stand_label, p_token_key_version, p_request_id);
$$;

/**
 * Append an audit event.
 *
 * `audit_events` has no INSERT grant for any client role, which is what makes
 * the history append-only from a user's point of view. The server appends
 * through this, and the organization is verified against the caller's own
 * membership rather than trusted.
 */
create or replace function app.record_audit_event(
    p_org_id      uuid,
    p_action      text,
    p_target_type text,
    p_target_id   text,
    p_request_id  text default null,
    p_metadata    jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    actor uuid := (select auth.uid());
begin
    if actor is null then
        raise exception 'authentication required' using errcode = '42501';
    end if;

    if not exists (
        select 1 from public.organization_members m
         where m.org_id = p_org_id and m.user_id = actor and m.status = 'active'
    ) then
        raise exception 'not a member of that organization' using errcode = '42501';
    end if;

    insert into public.audit_events
        (org_id, actor_user_id, actor_type, action, target_type, target_id, request_id, metadata)
    values
        (p_org_id, actor, 'user', p_action, p_target_type, p_target_id, p_request_id, p_metadata);
end;
$$;

create or replace function public.rpc_record_audit_event(
    p_org_id      uuid,
    p_action      text,
    p_target_type text,
    p_target_id   text,
    p_request_id  text default null,
    p_metadata    jsonb default '{}'::jsonb
)
returns void
language sql
security invoker
set search_path = ''
as $$
    select app.record_audit_event(p_org_id, p_action, p_target_type, p_target_id,
                                  p_request_id, p_metadata);
$$;

-- Callable by a signed-in user, unlike the anonymous flow's functions. Both
-- validate auth.uid() rather than accepting an actor as a parameter.
revoke all on function app.create_organization_with_first_stand(text, text, text, text, text, text, text, text, text, smallint, text) from public, anon;
revoke all on function app.record_audit_event(uuid, text, text, text, text, jsonb) from public, anon;
revoke all on function public.rpc_create_organization(text, text, text, text, text, text, text, text, text, smallint, text) from public, anon;
revoke all on function public.rpc_record_audit_event(uuid, text, text, text, text, jsonb) from public, anon;

grant execute on function public.rpc_create_organization(text, text, text, text, text, text, text, text, text, smallint, text) to authenticated;
grant execute on function public.rpc_record_audit_event(uuid, text, text, text, text, jsonb) to authenticated;
grant execute on function app.create_organization_with_first_stand(text, text, text, text, text, text, text, text, text, smallint, text) to authenticated;
grant execute on function app.record_audit_event(uuid, text, text, text, text, jsonb) to authenticated;
grant usage on schema app to authenticated;
